### ISSUE TITLE
Blank Fields

### ISSUE THREAD

**Issue by adeelkhalid9** [stevehansen/csv#12]
Breaks when reading Blank Fields

example:
 
,,First

**Comment by stevehansen** [comment]
I have tests for this: https://github.com/stevehansen/csv/blob/master/Csv.Tests/Tests.cs#L239
Can you provide the complete csv and code that you are using?

**Comment by adeelkhalid9** [comment]
``var csv = Csv.CsvReader.ReadFromText(",,First").ToArray();``

**Comment by adeelkhalid9** [comment]
the work arrount I found is:
`Csv.CsvReader.ReadFromText(",,First", new CsvOptions { HeaderMode = HeaderMode.HeaderAbsent }).ToArray();`

But this includes the header column 1, column 2.....

**Comment by stevehansen** [comment]
This is expected behavior, a csv without a header row will use Column1, Column2 and Column3 for your input, you can read the data using those names or by using the 0-based number index.

Can I close this issue?
