### ISSUE TITLE
HeaderMode.HeaderAbsent multi blank columns 

### ISSUE THREAD

**Issue by wazahuis** [stevehansen/csv#18]
Hi,

When I read a csv file with the HeaderMode.HeaderAbsent option, if the first row has two columns that are blank (I assume even with the same content) I get the error "an item with the same key has already been added". 

I assume this is because it is using the values of the first row as the field/column name.  It should just be manually using "Column1, Column2.." etc to avoid this.

**Comment by stevehansen** [comment]
That's exactly what HeaderAbsent should do, it will ignore the values of the first row and instead use hardcoded header names (Column1, ...)

I was adding a test case but it just passes:
```c#
[TestMethod]
[TestCategory("CsvOptions")]
public void AbsentHeaderIssue18()
{
    var lines = CsvReader.ReadFromText(",,\n4,5,6", new CsvOptions { HeaderMode = HeaderMode.HeaderAbsent }).ToArray();
    var headers = lines[0].Headers;

    Assert.AreNotEqual("", headers[0]);
    Assert.AreNotEqual("", headers[1]);
    Assert.AreNotEqual("", headers[2]);
}
```

Can you give a reproducible case (or the stack trace for the exception?)

**Comment by wazahuis** [comment]
sorry my bad, it was a logic error on my part (not passing the options)!
