### ISSUE TITLE
Support headerless CSV files (all rows are data)

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [stevehansen/csv#2]
Thanks for this little library, I'm working with some CSV files that will not have any header rows. So i'm modifying your project to optionally include the first row as data. 

Does it sound like an idea you would care for in csv?

**Comment by stevehansen** [comment]
Sure, send in a pull request when it's done

**Comment by stevehansen** [comment]
Thanks for the pull request. The new package is online but not indexed yet.
