### ISSUE TITLE
Doesn't handle "no data" well

### ISSUE THREAD

**Issue by axtens** [stevehansen/csv#20]
Assuming the CSV has a header but no data, there ought to be some way of telling that that has happened. As it stands, the best I can do is

            var hasData = false;
            var csvText = File.ReadAllText("c:\\tmp\\norecords.csv");
            foreach (var line in CsvReader.ReadFromText(csvText))
            {
                hasData = true;
            }
            if (hasData)
            {

            }

**Comment by axtens** [comment]
norecords.csv contains one line: col1,col2

**Comment by stevehansen** [comment]
You mean telling the difference between an empty file and one with just a single header?

**Comment by axtens** [comment]
With just a header. Said header may or may not have a newline.
