### ISSUE TITLE
Doesn't detect separator

### ISSUE THREAD

**Issue by Kagigz** [stevehansen/csv#21]
I tried reading a csv file with this package, but the separator is not detected, and even when I try passing in options specifying the separator, I keep getting only one column detected.

Note: This happened after opening the file in excel - works fine if the file wasn't opened in excel.

**Comment by stevehansen** [comment]
can you post some example code that is not working for you?

**Comment by Kagigz** [comment]
I tried with this:

```
var csv = File.ReadAllText("[...]/unique-tags-50.csv");
var dataset = CsvReader.ReadFromText(csv);
foreach (var line in dataset)
{
   Console.WriteLine($"\n{line[0]}: {line[1]}");
}
```
Then I tried again with the file that I re-downloaded, without opening it in Excel first, and it worked.
Maybe it's just that Excel messes up the file somehow.
