### ISSUE TITLE
HeaderMode.HeaderPresent columns with duplicate name

### ISSUE THREAD

**Issue by AngelBermudez57** [stevehansen/csv#22]
When there is a header and the header has duplicate header names it throws. InvalidOperationException("Duplicate headers detected in HeaderPresent mode. If you don't have a header you can set the HeaderMode to HeaderAbsent.");

Since the csv is provided to me can't be changed prior to processing the file, I added an option FixDuplicateColumnNames and some code to fix duplicate name issues. 

If there is another way other than coding please let me know?

I would be happy to check in the changes. Please let me know if you wish to have the changes checked in.

Thanks

**Comment by NickStrupat** [comment]
What about skipping the header and accessing the fields by numeric index instead of name?
