### ISSUE TITLE
Fields that have a comma after a escaped quotes still split the field.

### ISSUE THREAD

**Issue by Lyceq** [stevehansen/csv#28]
Using this as the input line: one,"two-a,two-b,""two-c"",two-d",three
The actual Lines property is [
  "one",
  "\"two-a, two-b, \"\"two-c\"\",
  "two-d\"",
  "three" ]
Expected Lines property is [
  "one",
  "two-a,two-b,\"two-c\",two-d",
  "three" ]

Test code that shows the issues is:

        [TestMethod]
        public void TestInternalSeperatorAfterEscapedQuote()
        {
            CsvOptions options = new CsvOptions();
            options.HeaderMode = HeaderMode.HeaderAbsent;
            foreach (ICsvLine line in CsvReader.ReadFromText("one,\"two - a, two - b, \"\"two - c\"\", two - d\",three", options))
                Assert.AreEqual(3, line.Values.Length);
        }

**Comment by stevehansen** [comment]
Csv 1.0.55 has been pushed to NuGet to fix this issue, thanks for reporting!
