### ISSUE TITLE
Strongly named assembly

### ISSUE THREAD

**Issue by amadare42** [stevehansen/csv#30]
Would you consider signing assembly (making it strongly-named)?
When trying to use library in strongly-named assembly, I'm getting following error:
`Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Csv, Version=1.0.58.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
`
More info: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

**Comment by stevehansen** [comment]
@amadare42 looks like I kept this open for too long, have you tried using https://github.com/dsplaisted/strongnamer as a workaround for now?
