### ISSUE TITLE
Backslash before quote with AllowBackSlashToEscapeQuote = false fails

### ISSUE THREAD

**Issue by LarsEriksenDSV** [stevehansen/csv#35]
When a field contains the combination \" at the end, parsing will fail.
The following test will provoke it in the second section:

        [TestMethod]
        public void BackslashBeforeQuote()
        {
            var withSpace = CsvReader.ReadFromText("\"A\";\"B\";\"C\"\n\"A \"\"\";\"B \\\"\" \";\"C\"", new CsvOptions { AllowNewLineInEnclosedFieldValues = true, AllowBackSlashToEscapeQuote = false, AllowSingleQuoteToEncloseFieldValues = false }).ToArray();
            Assert.AreEqual(1, withSpace.Length);
            Assert.AreEqual(3, withSpace[0].Headers.Length);
            Assert.AreEqual("A \"", withSpace[0][0]);
            Assert.AreEqual("B \\\" ", withSpace[0][1]);
            Assert.AreEqual("C", withSpace[0][2]);
            var withoutSpace = CsvReader.ReadFromText("\"A\";\"B\";\"C\"\n\"A \"\"\";\"B \\\"\"\";\"C\"", new CsvOptions { AllowNewLineInEnclosedFieldValues = true, AllowBackSlashToEscapeQuote = false, AllowSingleQuoteToEncloseFieldValues = false }).ToArray();
            Assert.AreEqual(1, withoutSpace.Length);
            Assert.AreEqual(3, withoutSpace[0].Headers.Length);
            Assert.AreEqual("A \"", withoutSpace[0][0]);
            Assert.AreEqual("B \\\"", withoutSpace[0][1]);
            Assert.AreEqual("C", withoutSpace[0][2]);
        }

**Comment by stevehansen** [comment]
@LarsEriksenDSV thank you very much, that's what the tests are for 😄

**Comment by stevehansen** [comment]
https://www.nuget.org/packages/Csv/2.0.65 has been published with the changed code, I added some extra tests for the differences when the flag is enabled/disabled

**Comment by LarsEriksenDSV** [comment]
> @LarsEriksenDSV thank you very much, that's what the tests are for 😄

You're welcome - and thank you for the speedy fix! - And this neat little Csv parser.
