### ISSUE TITLE
Doesn't handle cells with return very well

### ISSUE THREAD

**Issue by BillStark001** [stevehansen/csv#47]
For the input data(with CR-LF return)
```
key,value
test1,test2
test3,"test4

test5"
test6,test7
```
which is expected to be parsed to 
|key|value|
|-|-|
|test1|test2|
|test3|test4\r\n\r\ntest5|
|test6|test7|

is actually parsed to 

|key|value|
|-|-|
|test1|test2|
|test3|"test4|
|test5"||
|test6|test7|

**Comment by stevehansen** [comment]
NewLine support is not enabled by default, you'll need to set AllowNewLineInEnclosedFieldValues to true on the CsvOptions.

**Comment by BillStark001** [comment]
Thanks. It worked.
