### ISSUE TITLE
How to iterate headers? Property...

### ISSUE THREAD

**Issue by SiL3NC3** [stevehansen/csv#49]
Hi there,
I'm using you library reading data out of a csv file (as expected), with HeaderMode.HeaderPresent active.
The iteration through the items starts with the second line, where the data starts...
How can the headers being iterated?

Does not see any Header property having the list of all column names.
Would be a good thing to have directly (read) access to the headers.

Thank you for any hint.
// SiL

PS: Got it working, when switched the HeaderMode to HeaderAbsent ;)

**Comment by stevehansen** [comment]
HeaderMode.Absent can be used if you only access by index
otherwise you can use the first line and use its Headers property: https://github.com/stevehansen/csv/blob/master/Csv/ICsvLine.cs#L11

for example:
```c#
var csv = File.ReadAllText("sample.csv");
var firstLine = true;
foreach (var line in CsvReader.ReadFromText(csv))
{
  if (firstLine)
  {
    firstLine = false;

    // Validate headers
    if (line.Headers.Contains("SomeHeader"))
      break;
  }
  
  // Process line
}
```
