### ISSUE TITLE
How to write \n instead of \n\r inside cell

### ISSUE THREAD

**Issue by sgrodnik** [stevehansen/csv#50]
Hi, Steve! Thank you a lot for the great tool!
Could you please explain how to change (if possible) the new line character (NLC) in `CsvWriter.WriteToText`? Yes, we can do similar thing through the `CsvOptions` in `CsvReader.ReadFromText` and it is very useful. I read my tables with `\n\r` as a general NLC, and `\n `as a NLC inside multiline cells. I would want to write the same way, but `CsvWriter.WriteToText` does it waywardly: both cases with `\n\r`. Though it is not a wrong behaviour and data remains consistent, it does mess up the appearance of my tables a bit.

**Comment by stevehansen** [comment]
If you use the overload where you can pass your own TextWriter you can create your own StringWriter and set its NewLine property: https://docs.microsoft.com/en-us/dotnet/api/system.io.textwriter.newline?view=net-6.0#system-io-textwriter-newline

**Comment by sgrodnik** [comment]
Thanks for the quick response. Does this way fits my requirement about two varians of NLC simultaneously?
1) /n/r at the end of row;
2) /n at the end of the line of multiline cell.

**Comment by sgrodnik** [comment]
To clarify:
rows = "row1\tcell2\tcell3\n\rrow1\tcell2oftwo`\n`lines\tcell3"  // pseudocode
CsvWriter.WriteToText(columnNames, rows, '\t');  // returns unnecessary \r: "row1\tcell2\tcell3\n\rrow1\tcell2oftwo`\n\r`lines\tcell3"
