### ISSUE TITLE
[Syntax] `# comments are ignored`

### ISSUE THREAD

**Issue by chaojian-zhang** [stevehansen/csv#65]
Hi I know this is well-intended feature and I support it most of the time, but lately I am parsing CSV files that have real values starting with `#` in the first letter and because there is no way to toggle off skipping comments, such CSV files cannot be parsed.

I understand that the authoring program should have exported the values with `"` to "escape" them properly, but it's not done by the authoring program in this case and it would not be easy to try to escape those values in-place.

A hypothetical data would look like below:

```csv
HashTag,Author
#New,Charles
#Feature,Tom
```
Ideally there would be an option to `Csv.CsvOptions`:

```C#
Csv.CsvReader.ReadFromText(content, new Csv.CsvOptions()
{
    IgnoreComments = false
})
```

Appreciated!

**Comment by stevehansen** [comment]
the SkipRow property on the CsvOptions can be used for this, it's called for each row, by default is does:

```c#
SkipRow = (row, idx) => string.IsNullOrEmpty(row) || row[0] == '#',
```

But you can modify it to skip no rows or only empty rows...

```c#
// Never skip rows
SkipRow = (row, idx) => false,
```

**Comment by chaojian-zhang** [comment]
Thanks for quick reply!

I can confirm this works. I will close the issue.
