### ISSUE TITLE
new line characters should be escaped

### ISSUE THREAD

**Issue by jakubmisek** [stevehansen/csv#9]
https://github.com/stevehansen/csv/blob/a4169e1254db66e217283c15356f320af5dd5584/Csv/CsvWriter.cs#L64

**Comment by nolanblew** [comment]
Same. Just came across this issue!

**Comment by stevehansen** [comment]
The current CsvWriter implement everything that the CsvReader can process, at the moment it also doesn't support newlines inside a row

**Comment by stevehansen** [comment]
The CsvWriter will now escape new line but the reader can't read files (yet) with newlines

**Comment by stevehansen** [comment]
Fixed in 3dd493e8f2e59fcebb6a31e872129fc398c7bddb
